apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tess.fullname" . }}-route
spec:
  host: {{ .Values.app.host }}
  port:
    targetPort: {{ .Values.app.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "tess.fullname" . }}-service
status: {}

