
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: {{ .Values.backup.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-pod
              image: {{ .Values.backup.image }}
              envFrom:
                - secretRef:
                    name: {{ .Values.secrets.env }}
              env:
                - name: PGHOST
                  value: {{ .Values.db.service }}
                - name: PGPORT
                  value: {{ .Values.db.port | quote }}
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.env }}
                      key: DB_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.env }}
                      key: DB_PASSWORD
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secrets.env }}
                      key: DB_NAME
              command: ["/bin/sh", "-c"]
              args:
                - |
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S) && \
                  mkdir -p /backups && \
                  pg_dump -Fc "$DB_NAME" > "/backups/${DB_NAME}_${TIMESTAMP}.dump"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: Never
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: {{ .Values.backup.pvc }}
