apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
    type: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
      type: database
  template:
    metadata:
      name: db-pod
      labels:
        app: db
        type: database
    spec:
      containers:
        - name: {{ include "tess.fullname" . }}-db
          image: {{ .Values.db.image }}
          resources:
            requests:
              cpu: {{ .Values.db.requestCPU }}
              memory: {{ .Values.db.requestMem }}
            limits:
              cpu: {{ .Values.db.limitCPU }}
              memory: {{ .Values.db.limitMem }}
          ports:
            - containerPort: {{ .Values.db.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: db-data
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.env }}
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.env }}
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.env }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.env }}
                  key: DB_PASSWORD
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U $DB_USER -h 127.0.0.1
            periodSeconds: 5
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Values.db.pvc }}
