apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
    type: database
  ports:
    - name: {{ .Values.db.port | quote }}
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}