apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service }}
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}