apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
    type: caching
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
      type: caching
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
        type: caching
    spec:
      containers:
        - name: {{ include "tess.fullname" . }}-redis
          image: {{ .Values.redis.image }}
          resources:
            requests:
              cpu: {{ .Values.redis.requestCPU }}
              memory: {{ .Values.redis.requestMem }}
            limits:
              cpu: {{ .Values.redis.limitCPU }}
              memory: {{ .Values.redis.limitMem }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - mountPath: /data
              name: redis-data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            failureThreshold: 30
            periodSeconds: 1
            timeoutSeconds: 3
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Values.redis.pvc }}
