apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sidekiq.pvc }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sidekiq.pvcStorage }}
