apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.solr.service }}
spec:
  selector:
    app: solr
  ports:
    - protocol: TCP
      port: {{ .Values.solr.port }}
      targetPort: {{ .Values.solr.port }}